language:        node_js
sudo:            required
node_js:
  - "lts/*"
  - "node"
  - "8"
env:
  - ENV=CI

before_install:
  - npm install -g npm@latest

install:
  - sudo apt-get install sqlite3
  - npm install

script:
  - git clone https://github.com/orionsearch/TestDB ../TestDB
  - npm run test

notifications:
  email:         false
